### PR TITLE
Bump Apollo to 0.9.4 except GraphQLOperation model

### PR DESCRIPTION
**Pull request by larryonoff**
*Issue #, if available:* #36

*Description of changes:*

* implement clear() for AWSSQLLiteNormalizedCache
* update Apollo to 0.9.4 except GraphQLOperation model

`GraphQLOperation` was not update since it's not compatible with the model that generates aws-codegen

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by palpatim** [comment]
Is the Apollo upgrade necessary for the `clear`? If not, are there particular features or bug fixes in the newer version of Apollo that makes the upgrade a priority?

**Comment by larryonoff** [comment]
@palpatim 

> Is the Apollo upgrade necessary for the clear?

Yes. Because Apollo upgrade contains this feature.

**Comment by zigfreid5** [comment]
Looking forward to this making it into the next release 🤞🏻

**Comment by palpatim** [comment]
The primary reason for the change is the "clear" feature, and @larryonoff  has already done this on #141, which has a much reduced scope from this change, so I'm going to close this PR.

However, the core team would like to get back on an unforked version of Apollo if possible. So, within the next couple of months, we will  evaluate the changes we made to the Apollo code and see if we need to maintain the forked repository locally. As part of this, we'll see if we're able to isolate the changes into an easy-to-consume set of files, and add sufficient test coverage around our customized behavior that we are comfortable that upgrades won't cause any regressions to functionality we require for AppSync.

**Pull request closed without merging**
