### PR TITLE
Use "up to next major version rule" for `AWSiOSSDKV2`

### PR DESCRIPTION
**Pull request by alexanderedge**
Hi there,

We're unable to take advantage of bug fixes in the AWS SDK because the version rule is set to _up to next minor_. This PR changes the rule to _up to next major_ along with setting the version to 2.28.3 (the current release). This means that future minor and patch releases to the AWS SDK can be used with this AppSync package.

Is this acceptable to your team?

Thanks in advance,

Alex

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by Ricardo1980** [comment]
@alexanderedge 
Can you also add you change to the `podspec` file?
https://github.com/awslabs/aws-mobile-appsync-sdk-ios/blob/main/AWSAppSync.podspec#L14
Thanks a lot.

**Comment by alexanderedge** [comment]
Hi @royjit, is this PR something that your team would be able to consider merging? It would really help our team if we didn't have to fork this repository to keep up to date with the core AWS library. Thanks in advance.

**Comment by alexanderedge** [comment]
Hi @awslabs/amplify-ios just wondering if there's any scope to look at merging this PR?

**Comment by alexanderedge** [comment]
Hey @lawmicha I noticed you commented on [another PR](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/pull/558) and I was hoping that since this PR is trivial you might be able to take a look and approve if all looks good?

**Comment by alexanderedge** [comment]
> Hi @alexanderedge, the reason why this may break customers in the future is because the AWS iOS SDK does not follow semver, so a minor version may introduce breaking changes. This is why AppSync SDK takes on `upToNextMinor` to go up to but not including the next minor version, instead of `upToNextMajor` . Because of this, it requires us to do a release of AppSync SDK with the latest iOS SDK every time a minor version of iOS SDK is released. We recently did a release here in [3.6.2](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/releases/tag/3.6.2), please let us know if you have any other issues.

Thanks @lawmicha I had no idea that it didn't follow server so I really appreciate that explanation! I'll close this PR.

**Pull request closed without merging**
