### PR TITLE
Fix bug in subscription where data is not translated correctly to a format valid for JSONSerialization

### PR DESCRIPTION
**Pull request by LachlanMcCulloch**
*Issue #, if available:*
[Issue 401](https://github.com/awslabs/aws-mobile-appsync-sdk-ios/issues/401)

*Description of changes:*
See Issue for details

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by palpatim** [comment]
Need to explore unit tests for this to ensure it doesn't break with various subscription input variable types

**Comment by lawmicha** [comment]
Hi @LachlanMcCulloch, thanks for the PR. As mentioned above by @palpatim, I've added a few unit tests to capture the serialization scenario here https://github.com/LachlanMcCulloch/aws-mobile-appsync-sdk-ios/pull/1  please have a look

**Comment by LachlanMcCulloch** [comment]
Big thanks @lawmicha , I really appreciate it! I have reviewed your tests and they look good to me. I'm happy to merge into my branch as soon as it suits you

**Comment by LachlanMcCulloch** [comment]
@palpatim @lawmicha Can I merge these changes into the existing PR?

**Comment by LachlanMcCulloch** [comment]
@lawmicha I have merged the MR in 🙂

**Pull request merged**
